=== ChrigiGee/BuildAMation/Bam.Core/Schema/BamPackageDefinitionV1.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.buildamation.com"
    xmlns="http://www.buildamation.com"
    elementFormDefault="qualified">

<xs:attributeGroup name="required-package-attributes">
    <xs:attribute name="Name" type="xs:string" use="required" />
</xs:attributeGroup>

<xs:complexType name="required-package-version-type">
    <xs:sequence>
        <xs:element name="Version" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Id" type="xs:string" use="required" />
                <xs:attribute name="Condition" type="xs:string" use="optional" />
                <xs:attribute name="Default" type="xs:boolean" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="required-package-attributes" />
</xs:complexType>

<xs:complexType name="required-package-type">
    <xs:sequence>
        <xs:element name="Package" minOccurs="1" maxOccurs="unbounded" type="required-package-version-type">
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="required-bam-assemblies-type">
    <xs:sequence>
        <xs:element name="BamAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="required-dotnet-assemblies-type">
    <xs:sequence>
        <xs:element name="DotNetAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
                <xs:attribute name="RequiredTargetFramework" type="xs:string" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="definitions-type">
    <xs:sequence>
        <xs:element name="Definition" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="supported-platforms-type">
    <xs:sequence>
        <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="package-roots-type">
    <xs:sequence>
        <xs:element name="RootDirectory" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Path" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<!-- root node -->
<xs:element name="PackageDefinition">
    <xs:complexType>
        <xs:all>
            <xs:element name="PackageRoots" type="package-roots-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredPackages" type="required-package-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredBamAssemblies" type="required-bam-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredDotNetAssemblies" type="required-dotnet-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Definitions" type="definitions-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SupportedPlatforms" type="supported-platforms-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ChrigiGee/BuildAMation/packages/Qt/5.1.1/Qt.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <RequiredPackages>
    <Package Name="QtCommon">
      <Version Id="5.x" />
    </Package>
  </RequiredPackages>
  <RequiredBamAssemblies>
    <BamAssembly Name="Bam.Core" />
  </RequiredBamAssemblies>
  <RequiredDotNetAssemblies>
    <DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </RequiredDotNetAssemblies>
  <SupportedPlatforms>
    <Platform Name="Windows" />
    <Platform Name="Unix" />
    <Platform Name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/CSharpTest1/dev/CSharpTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <RequiredPackages>
    <Package Name="DotNetFramework">
      <Version Id="2.0.50727" />
      <Version Id="3.5" Default="true" />
      <Version Id="4.0" />
    </Package>
    <Package Name="MakeFileBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="NativeBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="Publisher">
      <Version Id="dev" />
    </Package>
    <Package Name="VSSolutionBuilder">
      <Version Id="dev" />
    </Package>
  </RequiredPackages>
  <RequiredBamAssemblies>
    <BamAssembly Name="Bam.Core" />
  </RequiredBamAssemblies>
  <RequiredDotNetAssemblies>
    <DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </RequiredDotNetAssemblies>
  <SupportedPlatforms>
    <Platform Name="Windows" />
    <Platform Name="Unix" />
    <Platform Name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/Test17/dev/Test17.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <RequiredPackages>
    <Package Name="Clang">
      <Version Id="Apple425" Default="true" />
      <Version Id="Apple503" />
    </Package>
    <Package Name="Gcc">
      <Version Id="4.4" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" Default="true" />
      <Version Id="4.6" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" />
      <Version Id="4.8" />
    </Package>
    <Package Name="LLVMGcc">
      <Version Id="4.2" Default="true" />
    </Package>
    <Package Name="MakeFileBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="Mingw">
      <Version Id="3.4.5" />
      <Version Id="4.5.0" />
      <Version Id="4.8.1" Default="true" />
    </Package>
    <Package Name="Test16">
      <Version Id="dev" />
    </Package>
    <Package Name="VisualC">
      <Version Id="11.0" />
      <Version Id="12.0" Default="true" />
    </Package>
    <Package Name="XcodeBuilder">
      <Version Id="dev" />
    </Package>
  </RequiredPackages>
  <RequiredBamAssemblies>
    <BamAssembly Name="Bam.Core" />
  </RequiredBamAssemblies>
  <RequiredDotNetAssemblies>
    <DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </RequiredDotNetAssemblies>
  <SupportedPlatforms>
    <Platform Name="Windows" />
    <Platform Name="Unix" />
    <Platform Name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/Cxx11Test1/dev/Cxx11Test1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <RequiredPackages>
    <Package Name="Clang">
      <Version Id="Apple425" />
    </Package>
    <Package Name="Gcc">
      <Version Id="4.8" />
    </Package>
    <Package Name="NativeBuilder">
      <Version Id="dev" />
    </Package>
  </RequiredPackages>
  <RequiredBamAssemblies>
    <BamAssembly Name="Bam.Core" />
  </RequiredBamAssemblies>
  <RequiredDotNetAssemblies>
    <DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </RequiredDotNetAssemblies>
  <SupportedPlatforms>
    <Platform Name="Windows" />
    <Platform Name="Unix" />
    <Platform Name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/Cxx11Test1/bam/Cxx11Test1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition name="Cxx11Test1" xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="C" />
    <Package name="Clang" version="Apple425" />
    <Package name="Gcc" version="4.8" />
    <Package name="MakeFileBuilder" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="12.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="WindowsSDK" version="8.1" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/zeromqtest/dev/zeromqtest.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <RequiredPackages>
    <Package Name="MakeFileBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="Publisher">
      <Version Id="dev" />
    </Package>
    <Package Name="QMakeBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="VisualC">
      <Version Id="10.0" />
      <Version Id="11.0" />
      <Version Id="12.0" Default="true" />
      <Version Id="8.0" />
      <Version Id="9.0" />
    </Package>
    <Package Name="VSSolutionBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="XcodeBuilder">
      <Version Id="dev" />
    </Package>
    <Package Name="zeromq">
      <Version Id="3.2.3" />
    </Package>
  </RequiredPackages>
  <RequiredBamAssemblies>
    <BamAssembly Name="Bam.Core" />
  </RequiredBamAssemblies>
  <RequiredDotNetAssemblies>
    <DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </RequiredDotNetAssemblies>
  <SupportedPlatforms>
    <Platform Name="Windows" />
    <Platform Name="Unix" />
    <Platform Name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>
