=== ChrigiGee/BuildAMation/Bam.Core/Schema/OpusPackageDependencyV2.xsd
<?xml version="1.0" encoding="iso-8859-1" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://code.google.com/p/opus"
    xmlns:Opus="http://code.google.com/p/opus"
    elementFormDefault="qualified">

<xs:attributeGroup name="required-package-attributes">
    <xs:attribute name="Name" type="xs:string" use="required" />
</xs:attributeGroup>
    
<xs:complexType name="required-package-version-type">
    <xs:sequence>
        <xs:element name="Version" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Id" type="xs:string" use="required" />
                <xs:attribute name="Condition" type="xs:string" use="optional" />
                <xs:attribute name="Default" type="xs:boolean" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="Opus:required-package-attributes" />
</xs:complexType>
    
<xs:complexType name="required-package-type">
    <xs:sequence>
        <xs:element name="Package" minOccurs="1" maxOccurs="unbounded" type="Opus:required-package-version-type">
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="required-opus-assemblies-type">
    <xs:sequence>
        <xs:element name="OpusAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="required-dotnet-assemblies-type">
    <xs:sequence>
        <xs:element name="DotNetAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
                <xs:attribute name="RequiredTargetFramework" type="xs:string" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="definitions-type">
    <xs:sequence>
        <xs:element name="Definition" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="supported-platforms-type">
    <xs:sequence>
        <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="package-roots">
    <xs:sequence>
        <xs:element name="RootDirectory" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="Path" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<!-- root node -->
<xs:element name="PackageDefinition">
    <xs:complexType>
        <xs:all>
            <xs:element name="PackageRoots" type="Opus:package-roots" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredPackages" type="Opus:required-package-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredOpusAssemblies" type="Opus:required-opus-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="RequiredDotNetAssemblies" type="Opus:required-dotnet-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Definitions" type="Opus:definitions-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SupportedPlatforms" type="Opus:supported-platforms-type" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ChrigiGee/BuildAMation/packages/Gcc/4.0.1/Gcc.xml
<?xml version="1.0" encoding="utf-8"?>
<Opus:PackageDefinition xsi:schemaLocation="http://code.google.com/p/opus file:///D:/dev/GoogleCode/Opus/trunk/bin/Debug/Schema/OpusPackageDependencyV2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Opus="http://code.google.com/p/opus">
  <Opus:RequiredPackages>
    <Opus:Package Name="GccCommon">
      <Opus:Version Id="dev" />
    </Opus:Package>
  </Opus:RequiredPackages>
  <Opus:RequiredOpusAssemblies>
    <Opus:OpusAssembly Name="Opus.Core" />
  </Opus:RequiredOpusAssemblies>
  <Opus:RequiredDotNetAssemblies>
    <Opus:DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <Opus:DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </Opus:RequiredDotNetAssemblies>
  <Opus:SupportedPlatforms>
    <Opus:Platform Name="OSX" />
  </Opus:SupportedPlatforms>
</Opus:PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/Test3/dev/Test3.xml
<?xml version="1.0" encoding="utf-8"?>
<Opus:PackageDefinition xsi:schemaLocation="http://code.google.com/p/opus file:///Users/mark/dev/Opus/trunk/bin/Debug/Schema/OpusPackageDependencyV2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Opus="http://code.google.com/p/opus">
  <Opus:RequiredPackages>
    <Opus:Package Name="C">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="Gcc">
      <Opus:Version Id="4.4" Condition="'$(Platform)' == 'Unix'" />
      <Opus:Version Id="4.0.1" Condition="'$(Platform)' == 'OSX'" />
    </Opus:Package>
    <Opus:Package Name="MakeFileBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="Mingw">
      <Opus:Version Id="3.4.5" />
    </Opus:Package>
    <Opus:Package Name="VisualC">
      <Opus:Version Id="9.0" />
    </Opus:Package>
    <Opus:Package Name="NativeBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="VSSolutionBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
  </Opus:RequiredPackages>
  <Opus:RequiredOpusAssemblies>
    <Opus:OpusAssembly Name="Opus.Core" />
  </Opus:RequiredOpusAssemblies>
  <Opus:RequiredDotNetAssemblies>
    <Opus:DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <Opus:DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </Opus:RequiredDotNetAssemblies>
  <Opus:SupportedPlatforms>
    <Opus:Platform Name="Windows" />
    <Opus:Platform Name="Unix" />
    <Opus:Platform Name="OSX" />
  </Opus:SupportedPlatforms>
</Opus:PackageDefinition>

=== ChrigiGee/BuildAMation/testpackages/Test10/dev/Test10.xml
<?xml version="1.0" encoding="utf-8"?>
<Opus:PackageDefinition xsi:schemaLocation="http://code.google.com/p/opus ./Schema/OpusPackageDependencyV2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Opus="http://code.google.com/p/opus">
  <Opus:RequiredPackages>
    <Opus:Package Name="C">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="Clang">
      <Opus:Version Id="3.1" />
    </Opus:Package>
    <Opus:Package Name="ComposerXE">
      <Opus:Version Id="12" />
    </Opus:Package>
    <Opus:Package Name="FileUtilities">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="Gcc">
      <Opus:Version Id="4.0" Condition="'$(Platform)' == 'OSX'" />
      <Opus:Version Id="4.1" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" />
      <Opus:Version Id="4.4" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" Default="true" />
      <Opus:Version Id="4.5" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" />
      <Opus:Version Id="4.6" Condition="'$(Platform)' == 'Windows' || '$(Platform)' == 'Unix'" />
    </Opus:Package>
    <Opus:Package Name="MakeFileBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="Mingw">
      <Opus:Version Id="3.4.5" Default="true" />
      <Opus:Version Id="4.5.0" />
    </Opus:Package>
    <Opus:Package Name="NativeBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="QMakeBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="VisualC">
      <Opus:Version Id="10.0" />
      <Opus:Version Id="11.0" />
      <Opus:Version Id="8.0" />
      <Opus:Version Id="9.0" Default="true" />
    </Opus:Package>
    <Opus:Package Name="VSSolutionBuilder">
      <Opus:Version Id="dev" />
    </Opus:Package>
    <Opus:Package Name="WindowsSDK">
      <Opus:Version Id="6.0A" Default="true" />
      <Opus:Version Id="7.1" />
    </Opus:Package>
  </Opus:RequiredPackages>
  <Opus:RequiredOpusAssemblies>
    <Opus:OpusAssembly Name="Opus.Core" />
  </Opus:RequiredOpusAssemblies>
  <Opus:RequiredDotNetAssemblies>
    <Opus:DotNetAssembly Name="System" RequiredTargetFramework="2.0.50727" />
    <Opus:DotNetAssembly Name="System.Xml" RequiredTargetFramework="2.0.50727" />
  </Opus:RequiredDotNetAssemblies>
  <Opus:SupportedPlatforms>
    <Opus:Platform Name="Windows" />
    <Opus:Platform Name="Unix" />
    <Opus:Platform Name="OSX" />
  </Opus:SupportedPlatforms>
</Opus:PackageDefinition>
